'use client';

import { useState } from 'react';
import Link from 'next/link';
import { Gift, MessageCircle, Send } from 'lucide-react';
const wa = (phone: string) => phone.replace(/\D/g, '').replace(/^0/, '27');

export default function ContributionOfferCard({ requestId, recipientName, phone }: { requestId: string; recipientName: string; phone?: string | null }) {
  const [amount, setAmount] = useState(''); const [message, setMessage] = useState(''); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  const submit = async () => { setBusy(true); setError(''); const response = await fetch('/api/contribution-offers', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ requestId, amount: Number(amount), message }) }); const data = await response.json(); if (response.ok) window.location.href = `/messages?conversation=${data.conversationId}`; else { setError(data.error || 'Unable to send offer.'); setBusy(false); } };
  return <div className="overflow-hidden rounded-3xl border border-primary-100 bg-white shadow-xl"><div className="bg-gradient-to-br from-gray-950 to-primary-950 p-6 text-white"><span className="inline-flex items-center gap-2 rounded-full bg-white/10 px-3 py-1 text-xs font-bold uppercase tracking-wider"><Gift className="h-4 w-4" /> Support directly</span><h2 className="mt-3 text-2xl font-black">See contact details</h2><p className="mt-2 text-sm leading-6 text-gray-300">Message {recipientName}, agree how you will help, and send an offer for them to confirm.</p>{phone && <a href={`https://wa.me/${wa(phone)}?text=${encodeURIComponent(`Hi ${recipientName}, I saw your request on MISHTEH and would like to help.`)}`} target="_blank" rel="noopener noreferrer" className="mt-4 inline-flex items-center gap-2 rounded-xl bg-green-600 px-4 py-3 text-sm font-bold text-white"><MessageCircle className="h-4 w-4" /> WhatsApp {phone}</a>}</div><div className="space-y-4 p-6"><div><label className="text-sm font-bold text-gray-900">How much would you like to offer?</label><div className="mt-2 flex rounded-xl border border-gray-300 focus-within:border-primary-500 focus-within:ring-4 focus-within:ring-primary-100"><span className="px-4 py-3 font-bold text-gray-600">R</span><input type="number" min="1" step="1" value={amount} onChange={(e) => setAmount(e.target.value)} placeholder="50" className="min-w-0 flex-1 rounded-r-xl px-2 py-3 text-lg font-bold outline-none" /></div></div><div><label className="text-sm font-bold text-gray-900">Message</label><textarea rows={4} maxLength={500} value={message} onChange={(e) => setMessage(e.target.value)} placeholder={`Hi ${recipientName}, I would like to help. How can we arrange it?`} className="mt-2 w-full rounded-xl border border-gray-300 p-3 text-sm outline-none focus:border-primary-500 focus:ring-4 focus:ring-primary-100" /></div>{error && <p className="rounded-xl bg-red-50 p-3 text-sm text-red-700">{error} {error.toLowerCase().includes('membership') && <Link href="/membership" className="font-bold underline">Renew for R10</Link>}</p>}<button onClick={submit} disabled={busy || Number(amount) < 1} className="flex w-full items-center justify-center gap-2 rounded-xl bg-primary-600 px-5 py-3.5 font-black text-white hover:bg-primary-700 disabled:opacity-50"><Send className="h-5 w-5" /> Send offer and message</button><p className="text-xs leading-5 text-gray-500">The amount is added only after {recipientName} accepts. MISHTEH does not process this payment.</p></div></div>;
}
